### ISSUE TITLE
Make nvim folder the root directory

### ISSUE THREAD

**Issue by zenoli** [zenoli/nvim-docker#10]
In order to make Zenovim a native neovim config, the nvim directory should become the root directory of this repository.

## Tasks
- [ ] create `docker` directory containing the scripts and everything related to the bootstrap docker image
- [ ] Create add `git clone` instruction which renames this folder from `zenovim` to `nvim`
- [ ] Add docker ignore

**Comment by zenoli** [comment]
Closing this issue as we decided to move zenovim to a dedicated repository and use it as a submodule instead.
See #17
