### ISSUE TITLE
Split into zenovim & zenovim-docker

### ISSUE THREAD

**Issue by zenoli** [zenoli/nvim-docker#16]
Split this project into two repos:
- zenovim: Plain neovim configuration
- zenovim-docker: Contains docker scripts, Dockerfiles and sample-project. Uses zenovim as a submodule.

## TODO

- [x] Rename this repo to zenovim-docker
- [x] Create repo zenovim
- [x] Add zenovim as submodule
- [x] Add clone command to README.md (with recusive submodule initialization)
